"""Product templates for common Indian shop categories.

Used during onboarding — new shop owners pick items from a checklist
instead of adding products one-by-one via WhatsApp.
"""

# Maps shop category → list of common item names
TEMPLATES: dict[str, list[str]] = {
    "Kirana / Grocery": [
        "Dal (Toor/Arhar) — 1 kg", "Dal (Moong) — 500 gm", "Dal (Masoor) — 500 gm",
        "Chana (Kabuli) — 500 gm",
        "Rice (Basmati) — 1 kg", "Rice (Parmal/Kolam) — 1 kg", "Rice (Boli) — 5 kg",
        "Wheat Flour (Atta) — 5 kg", "Wheat Flour (Atta) — 10 kg",
        "Maida — 1 kg", "Suji/Rava — 500 gm",
        "Sugar — 1 kg", "Sugar — 5 kg",
        "Salt (Namak) — 1 kg",
        "Cooking Oil (Mustard) — 1 L", "Cooking Oil (Sunflower) — 1 L", "Cooking Oil (Palm) — 1 L",
        "Ghee — 500 ml", "Ghee — 1 L",
        "Butter — 200 gm", "Cheese — 200 gm",
        "Milk Powder — 1 kg",
        "Tea (Chai Patti) — 250 gm", "Tea (Chai Patti) — 500 gm",
        "Coffee (Bru/Nescafe) — 50 gm", "Coffee (Bru/Nescafe) — 100 gm",
        "Biscuits (Parle-G) — 200 gm", "Biscuits (Marie) — 200 gm",
        "Cream Biscuits (Oreo/Good Day) — 200 gm",
        "Namkeen — 200 gm", "Chips (Lays/Kurkure) — 50 gm",
        "Cooking Spices (Haldi/Dhania/Mirchi) — 100 gm",
        "Garam Masala — 50 gm", "Chicken/Mutton Masala — 100 gm",
        "Pav Bhaji Masala — 100 gm",
        "Turmeric Powder (Haldi) — 200 gm",
        "Red Chilli Powder (Mirchi) — 200 gm",
        "Coriander Powder (Dhania) — 200 gm",
        "Cumin Seeds (Jeera) — 200 gm",
        "Mustard Seeds (Rai/Sarson) — 200 gm",
        "Fennel Seeds (Saunf) — 100 gm",
        "Fenugreek Seeds (Methi) — 200 gm",
        "Asafoetida (Hing) — 50 gm",
        "Toothpaste — 100 gm", "Toothbrush",
        "Soap (Bath) — 100 gm", "Soap (Washing)",
        "Shampoo Sachet", "Shampoo Bottle — 200 ml",
        "Hair Oil — 200 ml",
        "Detergent Powder — 500 gm", "Detergent Powder — 1 kg",
        "Dishwash Bar", "Dishwash Liquid — 500 ml",
        "Floor Cleaner — 1 L",
        "Candles — pack of 5", "Matchbox",
        "Agarbatti (Incense Sticks) — pack",
        "Coconut (Nariyal)",
        "Onion (Pyaz) — 1 kg", "Potato (Aloo) — 1 kg", "Tomato (Tamatar) — 1 kg",
        "Bread — 400 gm",
        "Jam/Ketchup — 500 gm",
        "Cold Drink Bottle — 2 L",
        "Water Bottle — 1 L", "Water Bottle — 5 L",
        "Eggs — tray of 30",
        "Noodles (Maggi/Yippee) — 70 gm",
        "Ketchup — 500 gm",
    ],
    "Fashion / Clothing": [
        "Men's Formal Shirt", "Men's Casual Shirt", "Men's T-Shirt",
        "Men's Jeans", "Men's Formal Trouser", "Men's Shorts",
        "Men's Kurta", "Men's Pyjama",
        "Men's Jacket", "Men's Sweater",
        "Men's Socks — pack of 3", "Men's Briefs — pack of 3", "Men's Vest — pack of 3",
        "Women's Kurti", "Women's Top", "Women's Jeans",
        "Women's Leggings", "Women's Palazzos",
        "Saree", "Saree Blouse Piece",
        "Salwar Suit", "Lehenga Choli",
        "Dupatta", "Women's Dupatta (Printed)",
        "Girls' Frock", "Girls' Lehenga",
        "Boys' Shirt", "Boys' T-Shirt", "Boys' Shorts",
        "Kids' Pyjama Set",
        "Innerwear (Women) — Bra", "Innerwear (Women) — Panty pack of 3",
        "Night Suit (Women)", "Night Suit (Men)",
        "Towel — cotton", "Towel — microfibre",
        "Handkerchief — pack of 5",
        "Cap/Hat", "Muffler/Scarf",
        "Belt (Men)", "Belt (Women)",
    ],
    "Electronics": [
        "Mobile Charger — Type C", "Mobile Charger — Micro USB", "Mobile Charger — Lightning",
        "USB Cable — Type C", "USB Cable — Micro USB",
        "Earphones — Wired", "Earphones — Bluetooth",
        "Power Bank — 10000 mAh", "Power Bank — 20000 mAh",
        "Data Cable — 1m", "Data Cable — 2m",
        "Mobile Cover — Universal", "Mobile Screen Guard",
        "Mobile Stand/Holder",
        "Extension Cord — 4 sockets", "Extension Cord — 6 sockets",
        "Bulb — LED 9W", "Bulb — LED 12W", "Bulb — LED 20W",
        "Tube Light — LED 20W",
        "Table Fan — 12 inch", "Table Fan — 16 inch",
        "USB Hub — 4 port",
        "Bluetooth Speaker",
        "Smart Watch",
        "Wall Charger — 2 port", "Wall Charger — 3 port",
        "Memory Card — 32 GB", "Memory Card — 64 GB",
        "Pen Drive — 32 GB", "Pen Drive — 64 GB",
        "Mouse — Wired", "Mouse — Wireless",
        "Keyboard — Wired", "Keyboard — Wireless",
        "Cable Organizer",
        "IR Remote (Universal)",
        "Electric Kettle",
    ],
    "Home & Kitchen": [
        "Steel Plate — dinner", "Steel Plate — small", "Melamine Plate — dinner",
        "Steel Glass — 250 ml", "Steel Glass — 500 ml", "Glass Tumbler — set of 6",
        "Steel Bowl — small", "Steel Bowl — medium", "Steel Bowl — large",
        "Pressure Cooker — 3 L", "Pressure Cooker — 5 L",
        "Kadhai (Wok) — medium", "Kadhai (Wok) — large",
        "Tawa (Flat Pan) — dosa", "Tawa (Flat Pan) — roti",
        "Frying Pan — non-stick small", "Frying Pan — non-stick large",
        "Saucepan — medium", "Saucepan — large",
        "Steel Thali",
        "Katori (Small Bowl) — set of 4",
        "Lunch Box — steel", "Lunch Box — plastic",
        "Water Bottle — steel 1 L",
        "Thermos/Flask — 1 L",
        "Knife — kitchen set", "Vegetable Chopper",
        "Cutting Board — plastic", "Cutting Board — wood",
        "Spoon Set — steel", "Ladle (Karchi)",
        "Jug — plastic 1 L",
        "Bucket — 10 L", "Bucket — 15 L",
        "Mug — plastic",
        "Tongs (Chimta)",
        "Grater",
        "Strainer (Chhalni)",
        "Rolling Pin (Belan) + Board",
        "Mortar & Pestle (Khalbatta / Okhli)",
        "Coconut Scraper (Nariyal Kasni)",
        "Steel Container — 1 kg", "Steel Container — 2 kg",
        "Plastic Container — 5 L",
        "Dustbin — small", "Dustbin — medium",
        "Cloth Hangers — pack of 6",
        "Clothes Drying Rack",
    ],
    "Beauty & Personal Care": [
        "Face Wash — 100 ml", "Face Wash — 200 ml",
        "Moisturizing Cream — 50 gm", "Moisturizing Cream — 100 gm",
        "Sunscreen — 50 ml",
        "Body Lotion — 200 ml", "Body Lotion — 400 ml",
        "Shampoo — 200 ml", "Shampoo — 400 ml", "Shampoo Sachet",
        "Conditioner — 200 ml",
        "Hair Oil — Coconut 200 ml", "Hair Oil — Amla 200 ml", "Hair Oil — Almond 200 ml",
        "Hair Gel — 100 gm", "Hair Spray",
        "Lip Balm", "Lipstick",
        "Kajal", "Eyeliner", "Mascara",
        "Foundation — 30 ml", "Compact Powder",
        "Nail Polish",
        "Deodorant/Perfume — Spray 100 ml",
        "Deodorant — Roll-on 50 ml",
        "Body Spray — 150 ml",
        "Sanitary Pads — pack of 10",
        "Baby Wipes — pack of 80",
        "Baby Oil — 100 ml", "Baby Powder — 200 gm",
        "Talcum Powder — 200 gm",
        "Cold Cream — 50 gm", "Cold Cream — 100 gm",
        "Rose Water — 100 ml",
        "Face Mask (Sheet) — pack of 5",
        "Cotton Balls — pack of 100",
        "Ear Buds (Cotton Swabs) — pack of 100",
        "Nail Cutter",
        "Hair Brush — medium", "Comb",
        "Razor — pack of 5", "Shaving Cream — 100 gm",
        "Aftershave — 50 ml",
        "Tweezers", "Scissors (Small)",
        "Soap — Bath 100 gm", "Soap — Bath 150 gm",
        "Hand Wash — 200 ml",
    ],
    "Books & Stationery": [
        "Notebook — Single Ruled 80 pages", "Notebook — Single Ruled 120 pages",
        "Notebook — Four Lines 80 pages",
        "Notebook — Square Grid 80 pages",
        "Long Notebook (Khata) — 172 pages", "Long Notebook (Khata) — 200 pages",
        "Drawing Book — small", "Drawing Book — large",
        "Pen — Ballpoint Blue", "Pen — Ballpoint Black", "Pen — Gel Blue",
        "Pen — Gel Black", "Pen — Fountain",
        "Pencil — HB", "Pencil — 2B", "Pencil — Colored Pack of 12",
        "Eraser", "Sharpener",
        "Scale — 15 cm", "Scale — 30 cm",
        "Geometry Box",
        "Crayons — pack of 12", "Sketch Pens — pack of 12",
        "Watercolor — 12 shades",
        "Glue Stick", "Fevicol — 50 ml",
        "Cellotape", "Double-sided Tape",
        "Stapler + Pins", "Paper Pins/Push Pins",
        "Punching Machine",
        "File Cover — Plain", "File Cover — Printed",
        "Plastic Folder — A4",
        "Register — 200 pages", "Register — 500 pages",
        "Sticky Notes (Post-it) — pack",
        "Highlighter — pack of 4",
        "Marker — Whiteboard", "Marker — Permanent Black", "Marker — Permanent Blue",
        "Calculator — basic", "Calculator — scientific",
        "Writing Pad — A4",
        "Envelope — pack of 20",
        "Brown Paper Sheet — pack of 10",
    ],
    "Food & Beverages": [
        "Packaged Water — 500 ml", "Packaged Water — 1 L", "Packaged Water — 5 L",
        "Cold Drink — 300 ml", "Cold Drink — 600 ml", "Cold Drink — 2 L",
        "Juice Pack — 200 ml", "Juice Pack — 1 L",
        "Energy Drink — 250 ml",
        "Seeds (Sunflower/Pumpkin) — 100 gm",
        "Dry Fruits Mix — 200 gm", "Cashew (Kaju) — 200 gm",
        "Almond (Badam) — 200 gm", "Pistachio (Pista) — 200 gm",
        "Raisins (Kishmish) — 200 gm",
        "Dates (Khajur) — 250 gm", "Dates (Khajur) — 500 gm",
        "Chikki — Peanut", "Chikki — Sesame",
        "Protein Bar", "Granola Bar",
        "Namkeen Mixture — 200 gm", "Bhujia — 200 gm",
        "Popcorn — 100 gm",
        "Chips — 50 gm pack", "Chips — 200 gm family pack",
        "Cookies — 200 gm",
        "Cake — 400 gm (packaged)",
        "Honey — 250 gm", "Honey — 500 gm",
        "Pickle (Achar) — Mixed 250 gm", "Pickle (Achar) — Mango 250 gm",
        "Murabba — 500 gm",
        "Papad — pack of 50",
        "Frozen Paratha — pack of 5",
        "Instant Noodles — pack of 12",
        "Soup Mix — pack of 5",
        "Ketchup/Tomato Sauce — 500 gm",
        "Mayonnaise — 200 gm",
        "Jam — Mixed Fruit 500 gm",
        "Corn Flakes — 500 gm",
        "Oats — 500 gm",
        "Muesli — 500 gm",
    ],
    "Medical / Pharmacy": [
        "Band-Aid — pack of 20", "Gauze Bandage — roll",
        "Cotton Roll — 100 gm",
        "Antiseptic Cream (Savlon/Boroline) — 50 gm",
        "Pain Relief Spray — 100 ml",
        "Pain Relief Gel (Volini/Moov) — 50 gm",
        "Dettol — 100 ml", "Dettol — 200 ml",
        "Sanitizer — 100 ml", "Sanitizer — 200 ml",
        "Face Mask — Surgical (pack of 50)", "Face Mask — N95",
        "Gloves — Latex (pack of 100)",
        "Thermometer — Digital",
        "BP Monitor — Automatic",
        "Glucose Powder — 200 gm",
        "ORS (Oral Rehydration Salts) — pack of 10",
        "Paracetamol — 500 mg strip", "Paracetamol — 650 mg strip",
        "Vitamin C — strip",
        "Antacid — strip",
        "Cough Syrup — 100 ml",
        "Allergy Relief — strip",
        "Multivitamin — bottle of 30",
        "Protein Powder — 500 gm",
        "Protein Shake — 250 ml",
        "First Aid Kit — small",
        "Ice Pack — reusable",
        "Hot Water Bottle",
        "Elastic Bandage — roll",
        "Crutch (Walking Stick)",
        "Wheelchair",
        "Adult Diaper — pack of 10",
        "Baby Diaper — pack of 40",
        "Baby Wipes — pack of 80",
        "Hand Sanitizer — 500 ml refill",
        "Disinfectant Spray — 200 ml",
    ],
    "Other": [
        # Generic items - shop writes their own
    ],
}


def get_templates_for_category(category: str) -> list[str]:
    """Return the product template list for a shop category.

    Args:
        category: The shop category string.

    Returns:
        List of common product names for that category.
    """
    return TEMPLATES.get(category, [])


def get_all_categories() -> list[str]:
    """Return all known category names."""
    return [c for c in TEMPLATES if c != "Other"]
